inherits = "boo_berry"

# Override the theming for "keyword"s:
"keyword" = { fg = "gold" }
"ui.cursor.select" = { fg = "black", bg = "white" }
"ui.selection" = { fg = "black", bg = "white" }

# Override colors in the palette:
[palette]
#berry = "#2A2A4D"
black = "#000000"
white = "#FFFFFF"
