# theme = "heisenberg"
# theme = "boo_berry"
# theme = "jellybeans"
# theme = "regi2"
# theme = "doom_acario_dark"

# theme = "regi-doom_acario_dark"
# theme = "regi-boo_berry"
# theme  = "snazzy"
# theme  = "regi-bogster"
# theme  = "regi-snazzy"
  theme  = "vim_dark_high_contrast"

[editor]
line-number = "relative"


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.gutters.line-numbers]
min-width = 5

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-o = ":open ~/.config/helix/config.toml" # Maps Ctrl-o to opening of the helix config file

# a = "move_char_left" # Maps the 'a' key to the move_char_left command
# w = "move_line_up" # Maps the 'w' key move_line_up

# "C-S-esc" = "extend_line" # Maps Ctrl-Shift-Escape to extend_line
# g = { a = "code_action" } # Maps `ga` to show possible code actions
# "ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode

[keys.insert]
# "A-x" = "normal_mode"     # Maps Alt-X to enter normal mode
# j = { k = "normal_mode" } # Maps `jk` to exit insert mode

